import React, { useState } from "react"
import { FileText, Database, BookOpen, Cpu, Check, Copy, Sparkles, Download, ArrowRight, ShieldCheck } from "lucide-react"

export const ExportStudioPreview: React.FC = () => {
  const [activeTab, setActiveTab] = useState<"markdown" | "jsonl" | "pdf" | "mcp">("jsonl")
  const [copied, setCopied] = useState(false)
  const [mcpQuery, setMcpQuery] = useState("authentication oauth")
  const [mcpResponse, setMcpResponse] = useState<string | null>(null)

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleSimulateMcp = (query: string) => {
    setMcpQuery(query)
    const simulated = JSON.stringify(
      {
        jsonrpc: "2.0",
        id: "call_98x72a",
        result: {
          tool: "search_docs",
          query: query,
          matches_count: 3,
          results: [
            {
              domain: "docs.openalgo.in",
              path: "pages/auth/oauth.md",
              title: "OAuth 2.0 Authentication & Token Lifecycle",
              score_bm25: 14.82,
              snippet: "All requests require Bearer token. Refresh token via /oauth/v2/token...",
              source_url: "https://docs.openalgo.in/v/v2.0/auth/oauth",
              content_hash: "sha256-e3b0c44298fc1c149afbf4c8996fb924"
            },
            {
              domain: "docs.openalgo.in",
              path: "pages/auth/api-keys.md",
              title: "API Key Management & Rotation",
              score_bm25: 11.45,
              snippet: "Pass x-api-key in request headers for server-to-server calls...",
              source_url: "https://docs.openalgo.in/v/v2.0/auth/api-keys",
              content_hash: "sha256-4a5f6e7d8c9b0a1f2e3d4c5b"
            }
          ]
        }
      },
      null,
      2
    )
    setMcpResponse(simulated)
  }

  const previews = {
    markdown: {
      filename: "book.md",
      badge: "Single Unified Handbook",
      lang: "markdown",
      tokenStat: "48% token savings vs raw HTML",
      content: `# OpenAlgo API & Developer Handbook
*Generated by DocHarvest v9.0.1 on 2026-08-23*

## Table of Contents
1. [1.0 Getting Started](#10-getting-started)
   - [1.1 Quickstart Guide](#11-quickstart-guide)
   - [1.2 Environment Configuration](#12-environment-configuration)
2. [2.0 Authentication & Security](#20-authentication--security)
   - [2.1 OAuth 2.0 Authentication](#21-oauth-20-authentication)
   - [2.2 API Key Secret Rotation](#22-api-key-secret-rotation)
3. [3.0 Broker Connectivity](#30-broker-connectivity)
   - [3.1 Order Placement Endpoints](#31-order-placement-endpoints)
   - [3.2 WebSocket Streaming Engine](#32-websocket-streaming-engine)

---

## 1.0 Getting Started
### 1.1 Quickstart Guide
Welcome to the OpenAlgo technical documentation. OpenAlgo is a low-latency gateway for automated broker execution.

\`\`\`python
import openalgo

client = openalgo.Client(api_key="oa_sec_99182")
status = client.health_check()
print(f"Gateway status: {status.state}")
\`\`\`

## 2.0 Authentication & Security
### 2.1 OAuth 2.0 Authentication
All API requests require a valid Bearer token passed in the Authorization header.`
    },
    jsonl: {
      filename: "exports/openalgo_rag.jsonl",
      badge: "Vector & RAG Ready",
      lang: "jsonl",
      tokenStat: "Zero HTML noise • Header envelopes",
      content: `{"id": "doc_openalgo_001", "domain": "docs.openalgo.in", "title": "OAuth 2.0", "path": "auth/oauth.md", "chunk_index": 1, "total_chunks": 3, "token_count": 412, "content_hash": "sha256-e3b0c442", "text": "<!-- domain: docs.openalgo.in, source: auth/oauth.md, chunk: 1/3 -->\\n# OAuth 2.0 Authentication\\n\\nAll API requests require a valid bearer token. Tokens expire after 3600s.\\n\\n\`\`\`bash\\ncurl -X POST https://api.openalgo.in/v2/oauth/token \\\\n  -d 'grant_type=client_credentials'\\n\`\`\`"}
{"id": "doc_openalgo_002", "domain": "docs.openalgo.in", "title": "Order Execution", "path": "trading/orders.md", "chunk_index": 1, "total_chunks": 4, "token_count": 520, "content_hash": "sha256-8f3b2a1c", "text": "<!-- domain: docs.openalgo.in, source: trading/orders.md, chunk: 1/4 -->\\n# Order Execution API\\n\\nSubmit market, limit, and trigger bracket orders with atomic transaction safety."}
{"id": "doc_openalgo_003", "domain": "docs.openalgo.in", "title": "WebSocket Stream", "path": "realtime/feed.md", "chunk_index": 1, "total_chunks": 2, "token_count": 340, "content_hash": "sha256-1c2d3e4f", "text": "<!-- domain: docs.openalgo.in, source: realtime/feed.md, chunk: 1/2 -->\\n# WebSocket Feeds\\n\\nConnect to wss://feed.openalgo.in/v2/market for sub-millisecond orderbook quotes."}`
    },
    pdf: {
      filename: "exports/openalgo_handbook.pdf",
      badge: "Pure Python fpdf2",
      lang: "text",
      tokenStat: "Zero C-dependencies • Publication grade",
      content: `╔══════════════════════════════════════════════════════════════════════╗
║                          OPENALGO HANDBOOK                           ║
║             Compiled by DocHarvest (Pure-Python fpdf2)               ║
║                                                                      ║
║  Page 14 of 420                                                      ║
║ ──────────────────────────────────────────────────────────────────── ║
║                                                                      ║
║  2.1 OAuth 2.0 Authentication Flow                                   ║
║                                                                      ║
║  All HTTP endpoints require bearer token authentication.             ║
║                                                                      ║
║  ┌── [ Python 3.10+ SDK Example ] ────────────────────────────────┐  ║
║  │ import requests                                                │  ║
║  │                                                                │  ║
║  │ res = requests.post(                                           │  ║
║  │     "https://api.openalgo.in/v2/oauth/token",                  │  ║
║  │     headers={"Authorization": "Bearer SEC_TOKEN_99"}           │  ║
║  │ )                                                              │  ║
║  │ print(res.json())                                              │  ║
║  └────────────────────────────────────────────────────────────────┘  ║
║                                                                      ║
║  Table 2.1: HTTP Response Status Codes                               ║
║  ┌────────┬────────────────┬──────────────────────────────────────┐  ║
║  │ Code   │ Status         │ Meaning                              │  ║
║  ├────────┼────────────────┼──────────────────────────────────────┤  ║
║  │ 200    │ OK             │ Token issued successfully            │  ║
║  │ 401    │ Unauthorized   │ Invalid client secrets               │  ║
║  │ 429    │ Too Many Reqs  │ Exceeded 100 req/min quota           │  ║
║  └────────┴────────────────┴──────────────────────────────────────┘  ║
╚══════════════════════════════════════════════════════════════════════╝`
    },
    mcp: {
      filename: "FastMCP stdio JSON-RPC",
      badge: "Cursor & Claude Ready",
      lang: "json",
      tokenStat: "8 native tools for autonomous AI agents",
      content: mcpResponse || JSON.stringify(
        {
          jsonrpc: "2.0",
          id: "call_98x72a",
          result: {
            tool: "search_docs",
            query: "authentication oauth",
            matches_count: 2,
            results: [
              {
                domain: "docs.openalgo.in",
                path: "pages/auth/oauth.md",
                title: "OAuth 2.0 Authentication",
                score_bm25: 14.82,
                source_url: "https://docs.openalgo.in/v/v2.0/auth/oauth",
                content_hash: "sha256-e3b0c44298fc1c149afbf4c8996fb924"
              },
              {
                domain: "docs.openalgo.in",
                path: "pages/auth/api-keys.md",
                title: "API Key Management",
                score_bm25: 11.45,
                source_url: "https://docs.openalgo.in/v/v2.0/auth/api-keys",
                content_hash: "sha256-4a5f6e7d8c9b0a1f2e3d4c5b"
              }
            ]
          }
        },
        null,
        2
      )
    }
  }

  const currentPreview = previews[activeTab]

  return (
    <section id="export-studio" className="py-24 relative bg-[#09090b]">
      {/* Top divider */}
      <div className="absolute top-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-zinc-800 to-transparent" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-lg bg-amber-500/10 border border-amber-500/30 text-amber-400 text-xs font-mono font-semibold mb-4">
            <Sparkles className="w-3.5 h-3.5" />
            <span>EXPORT &amp; COMPILATION STUDIO</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight mb-4">
            Multi-Target Knowledge Studio
          </h2>
          <p className="text-zinc-400 text-base sm:text-lg">
            Convert captured documentation into vector datasets for LangChain &amp; ChromaDB, single consolidated Markdown books, styled PDF handbooks, or an autonomous FastMCP server.
          </p>
        </div>

        {/* Live Studio Container */}
        <div className="rounded-2xl bg-zinc-900/90 border border-zinc-800 overflow-hidden shadow-2xl">
          {/* Studio Navigation Bar */}
          <div className="p-4 sm:p-6 bg-zinc-900 border-b border-zinc-800 flex flex-col md:flex-row md:items-center justify-between gap-4">
            {/* Format Switcher Tabs */}
            <div className="flex flex-wrap items-center gap-2 bg-zinc-950 p-1.5 rounded-xl border border-zinc-800">
              <button
                onClick={() => setActiveTab("jsonl")}
                className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-xs font-mono font-medium transition-all ${
                  activeTab === "jsonl"
                    ? "bg-amber-500 text-zinc-950 font-bold shadow"
                    : "text-zinc-400 hover:text-zinc-200"
                }`}
              >
                <Database className="w-3.5 h-3.5" />
                <span>RAG Vector JSONL</span>
              </button>

              <button
                onClick={() => setActiveTab("markdown")}
                className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-xs font-mono font-medium transition-all ${
                  activeTab === "markdown"
                    ? "bg-cyan-500 text-zinc-950 font-bold shadow"
                    : "text-zinc-400 hover:text-zinc-200"
                }`}
              >
                <FileText className="w-3.5 h-3.5" />
                <span>book.md (TOC)</span>
              </button>

              <button
                onClick={() => setActiveTab("pdf")}
                className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-xs font-mono font-medium transition-all ${
                  activeTab === "pdf"
                    ? "bg-rose-500 text-zinc-950 font-bold shadow"
                    : "text-zinc-400 hover:text-zinc-200"
                }`}
              >
                <BookOpen className="w-3.5 h-3.5" />
                <span>Printable PDF (fpdf2)</span>
              </button>

              <button
                onClick={() => setActiveTab("mcp")}
                className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-xs font-mono font-medium transition-all ${
                  activeTab === "mcp"
                    ? "bg-indigo-500 text-zinc-950 font-bold shadow"
                    : "text-zinc-400 hover:text-zinc-200"
                }`}
              >
                <Cpu className="w-3.5 h-3.5" />
                <span>FastMCP JSON-RPC</span>
              </button>
            </div>

            {/* Token Stat & Copy Button */}
            <div className="flex items-center gap-3">
              <span className="hidden sm:inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-cyan-500/10 border border-cyan-500/20 text-xs font-mono text-cyan-400">
                <Sparkles className="w-3 h-3" />
                <span>{currentPreview.tokenStat}</span>
              </span>

              <button
                onClick={() => handleCopy(currentPreview.content)}
                className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-xs font-mono text-zinc-200 hover:text-white transition-all"
              >
                {copied ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span className="text-emerald-400">Copied</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5 text-zinc-400" />
                    <span>Copy Payload</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Interactive FastMCP Simulator Bar when on MCP tab */}
          {activeTab === "mcp" && (
            <div className="px-6 py-3 bg-[#13131a] border-b border-zinc-800 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 text-xs">
              <div className="flex items-center gap-2 flex-1">
                <span className="font-mono text-zinc-400 shrink-0">Simulate MCP Tool Call:</span>
                <input
                  type="text"
                  value={mcpQuery}
                  onChange={(e) => setMcpQuery(e.target.value)}
                  placeholder="e.g. authentication oauth, websocket, orders"
                  className="bg-zinc-950 border border-zinc-700/80 rounded px-2.5 py-1 text-xs font-mono text-cyan-300 flex-1"
                />
              </div>
              <button
                onClick={() => handleSimulateMcp(mcpQuery)}
                className="px-3.5 py-1 rounded bg-indigo-600 hover:bg-indigo-500 text-white font-mono font-semibold transition-colors"
              >
                Execute Tool Call
              </button>
            </div>
          )}

          {/* Code & Preview Screen */}
          <div className="p-6 bg-[#09090d] font-mono text-xs sm:text-sm text-zinc-200 overflow-x-auto min-h-[380px] select-text">
            <pre className="leading-relaxed whitespace-pre-wrap selection:bg-cyan-500/30">
              {currentPreview.content}
            </pre>
          </div>

          {/* Studio Footer Info */}
          <div className="p-4 bg-zinc-950 border-t border-zinc-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs font-mono text-zinc-400">
            <div className="flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-emerald-400" />
              <span>Target: {currentPreview.filename}</span>
            </div>
            <div className="flex items-center gap-4 text-zinc-500">
              <span>Encoding: UTF-8</span>
              <span>Frontmatter: SHA-256 Verified</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
